### ISSUE TITLE
Collections: Starts from the end?

### ISSUE THREAD

**Issue by zogot** [noglitchyo/middleware-collection-request-handler#1]
Hey, just wanted to clarify, the collection should start from the end of the array? I see in the tests you are expecting it, but I would then definitely recommend to make that clear in the README.

**Comment by zogot** [comment]
I do see you refer to the FIFO, LIFO in your documentation. I missed that part.

**Comment by noglitchyo** [comment]
Hey @zogot,

It seems that your issue is resolved. I will then close this issue. 

I tried to update a little bit the documentation, so it might be more clear.
However, if you still think the documentation could be more clear or extended on this point, do not hesitate to submit a pull-request.

Max
